# Generated by Django 4.0.2 on 2022-02-21 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.CharField(blank=True, max_length=64, verbose_name='кол-во комнат')),
                ('price', models.CharField(blank=True, max_length=20, verbose_name='цена')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='Адрес')),
                ('desc', models.TextField(blank=True, verbose_name='описание')),
                ('floor', models.CharField(blank=True, max_length=10, verbose_name='этаж')),
                ('commission', models.CharField(blank=True, max_length=256, verbose_name='коммисия')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'квартира',
                'verbose_name_plural': 'квартиры',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('url', models.URLField(verbose_name='ссылка')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ссылка',
                'verbose_name_plural': 'ссылки',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, verbose_name='имя')),
                ('last_name', models.CharField(blank=True, max_length=240, verbose_name='фамилия')),
                ('phone_1', models.CharField(blank=True, max_length=18, verbose_name='телефон 1')),
                ('phone_2', models.CharField(blank=True, max_length=18, verbose_name='телефон 2')),
                ('avatar', models.ImageField(default='avatars/avatar.png', upload_to='avatars/%Y/%m/%d', verbose_name='аватар')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='image/')),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cian.apartment')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'фото',
            },
        ),
    ]
