# Generated by Django 4.0.2 on 2022-02-21 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, verbose_name='имя')),
                ('last_name', models.CharField(blank=True, max_length=240, verbose_name='фамилия')),
                ('phone_1', models.CharField(blank=True, max_length=18, verbose_name='телефон 1')),
                ('phone_2', models.CharField(blank=True, max_length=18, verbose_name='телефон 2')),
                ('avatar', models.ImageField(default='avatars/avatar.png', upload_to='avatars/%Y/%m/%d', verbose_name='аватар')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
            },
        ),
    ]
